package registry

// communityModuleCatalog lists additional projects from avelino/awesome-go
// with module paths taken from each project's go.mod.
const communityModuleCatalog = `
claude-code-go|github.com/lancekrogers/claude-code-go
cynative|github.com/cynative/cynative
thermal|github.com/jadmadi/thermal
gocue|github.com/iSerganov/gocue
Fling-CLI|github.com/SatyamKumarCS/Fling-CLI
GoPOSIX|github.com/ramayac/goposix
go-yamlvalidator|github.com/Yakwilik/go-yamlvalidator
glinq|github.com/CreateLab/glinq
xsync|github.com/puzpuzpuz/xsync/v4
avro|github.com/khezen/avro
bytebase|github.com/bytebase/bytebase
db-migrator.go|github.com/raoptimus/db-migrator.go
dbmate|github.com/amacneil/dbmate/v2
go-fixtures|github.com/RichardKnop/go-fixtures
go-pg-migrate|github.com/lawzava/go-pg-migrate/v3
go-pg-migrations|github.com/robinjoseph08/go-pg-migrations/v3
goavro|github.com/linkedin/goavro/v2
godfish|github.com/rafaelespinoza/godfish
goose|github.com/pressly/goose/v3
gorm-seeder|github.com/kachit/gorm-seeder
gormigrate|github.com/go-gormigrate/gormigrate/v2
libschema|github.com/muir/libschema
migrator|github.com/lopezator/migrator
schema|github.com/adlio/schema
skeema|github.com/skeema/skeema
sql-migrate|github.com/rubenv/sql-migrate
sqlize|github.com/sunary/sqlize
chproxy|github.com/contentsquare/chproxy
clickhouse-bulk|github.com/nikepan/clickhouse-bulk
clickhouse-sql-parser|github.com/AfterShip/clickhouse-sql-parser
database-gateway|github.com/kazhuravlev/database-gateway
dbbench|github.com/sj14/dbbench
dg|github.com/codingconcepts/dg
filesql|github.com/nao1215/filesql
gatewayd|github.com/gatewayd-io/gatewayd
go-mysql|github.com/go-mysql-org/go-mysql
go-postgres-s3-backup|github.com/nicobistolfi/go-postgres-s3-backup
gorm-multitenancy|github.com/bartventer/gorm-multitenancy/v8
GoSQLX|github.com/ajitpratap0/GoSQLX
octillery|go.knocknote.io/octillery
onedump|github.com/liweiyi88/onedump
pg_timetable|github.com/cybertec-postgresql/pg_timetable
pgrwl|github.com/pgrwl/pgrwl
pgwd|github.com/hrodrig/pgwd
pgweb|github.com/sosedoff/pgweb
pgxcli|github.com/balajz/pgxcli
prest|github.com/prest/prest/v2
rdb|github.com/hdt3213/rdb
sqly|github.com/nao1215/sqly
vitess|vitess.io/vitess
xsql|github.com/zx06/xsql
bqb|github.com/nullism/bqb
buildsqlx|github.com/arthurkushman/buildsqlx
builq|github.com/cristalhq/builq
dba|github.com/kran/dba
dbq|github.com/rocketlaunchr/dbq
dotsql|github.com/qustavo/dotsql
gendry|github.com/didi/gendry
goqu|github.com/doug-martin/goqu/v9
gosql|github.com/twharmon/gosql
hotcoal|github.com/motrboat/hotcoal
igor|github.com/galeone/igor
jet|github.com/go-jet/jet/v2
obreron|github.com/profe-ajedrez/obreron
ormlite|github.com/pupizoid/ormlite
ozzo-dbx|github.com/go-ozzo/ozzo-dbx
patcher|github.com/jacobbrewer1/patcher
qrafter|github.com/SennovE/qrafter
qry|github.com/HnH/qry
relica|github.com/coregx/relica
sg|github.com/go-the-way/sg
go-structured-query|github.com/bokwoon95/go-structured-query
sqlcredo|github.com/Klojer/sqlcredo
sqlf|github.com/leporo/sqlf
sqlh|github.com/kirill-scherba/sqlh
sqrl|github.com/elgris/sqrl
squirrel|github.com/Masterminds/squirrel
xo|github.com/xo/dbtpl
cayley|github.com/cayleygraph/cayley
dsc|github.com/viant/dsc
dynamo|github.com/fogfish/dynamo/v3
gokv|github.com/philippgille/gokv
transactor|github.com/metalfm/transactor
calcite-avatica-go|github.com/apache/calcite-avatica-go/v5
bgc|github.com/viant/bgc
firebirdsql|github.com/nakagami/firebirdsql
go-adodb|github.com/mattn/go-adodb
go-mssqldb|github.com/denisenkom/go-mssqldb
go-oci8|github.com/mattn/go-oci8
gorqlite|github.com/rqlite/gorqlite
go-sqlite3|github.com/mattn/go-sqlite3
godror|github.com/godror/godror
ksql|github.com/vingarcia/ksql
pig|github.com/otetz/pig
sqinn-go|github.com/cvilsmeier/sqinn-go/v2
sqlhooks|github.com/qustavo/sqlhooks/v2
surrealdb.go|github.com/surrealdb/surrealdb.go
ydb-go-sdk|github.com/ydb-platform/ydb-go-sdk/v3
aerospike-client-go|github.com/aerospike/aerospike-client-go
arangolite|github.com/solher/arangolite/v2
go-couchbase|github.com/couchbase/go-couchbase
go-mongox|github.com/chenmingyong0423/go-mongox/v2
go-pilosa|github.com/pilosa/go-pilosa
go-rejson|github.com/nitishm/go-rejson/v4
gocb|github.com/couchbase/gocb/v2
gocosmos|github.com/btnguyen2k/gocosmos
godis|github.com/piaohao/godis
gomemcache|github.com/bradfitz/gomemcache
gomemcached|github.com/aliexpressru/gomemcached
gorethink|gopkg.in/rethinkdb/rethinkdb-go.v6
goriak|github.com/zegl/goriak/v3
kivik|github.com/go-kivik/kivik/v4
mgm|github.com/kamva/mgm/v3
qmgo|github.com/qiniu/qmgo
redeo|github.com/bsm/redeo/v2
redigo|github.com/gomodule/redigo
rueidis|github.com/redis/rueidis
xredis|github.com/shomali11/xredis
clickhouse-go|github.com/ClickHouse/clickhouse-go/v2
effdsl|github.com/sdqri/effdsl/v2
elasticsql|github.com/cch123/elasticsql
go-elasticsearch|github.com/elastic/go-elasticsearch/v9
zoekt|github.com/sourcegraph/zoekt
approx|github.com/goschtalt/approx
carbon|github.com/dromara/carbon/v2
cronrange|github.com/1set/cronrange
date|github.com/rickb777/date
dateparse|github.com/araddon/dateparse
durafmt|github.com/hako/durafmt
feiertage|github.com/wlbr/feiertage
go-anytime|github.com/ijt/go-anytime
go-date-fns|github.com/chmenegatti/go-date-fns
go-datebin|github.com/deatil/go-datebin
go-faketime|github.com/harkaitz/go-faketime
go-persian-calendar|github.com/yaa110/go-persian-calendar
go-str2duration|github.com/xhit/go-str2duration/v2
go-sunrise|github.com/nathan-osman/go-sunrise
go-week|github.com/stoewer/go-week
gostradamus|github.com/bykof/gostradamus
iso8601|github.com/relvacode/iso8601
now|github.com/jinzhu/now
timex|github.com/invzhi/timex
tuesday|github.com/osteele/tuesday
arpc|github.com/lesismal/arpc
bedrock|github.com/z5labs/bedrock
capillaries|github.com/capillariesio/capillaries
circuit|github.com/schigh/circuit
cmd-stream-go|github.com/cmd-stream/cmd-stream-go
committer|github.com/vadiminshakov/committer
consistent|github.com/buraksezer/consistent
consistenthash|github.com/mbrostami/consistenthash/v2
dht|github.com/anacrolix/dht/v2
dot|github.com/dotchain/dot
doublejump|github.com/edwingeng/doublejump
dragonboat|github.com/lni/dragonboat/v4
Dragonfly2|d7y.io/dragonfly/v2
drmaa|github.com/dgruber/drmaa
emitter|github.com/emitter-io/emitter
evans|github.com/ktr0731/evans
failured|github.com/andy2046/failured
flowgraph|github.com/vectaport/flowgraph
gleam|github.com/chrislusf/gleam
micro|github.com/gmsec/micro
go-doudou|github.com/unionj-cloud/go-doudou/v2
eagle|github.com/go-eagle/eagle
kit|github.com/go-kit/kit
go-micro|go-micro.dev/v6
go-mysql-lock|github.com/sanketplus/go-mysql-lock
go-pdu|github.com/pdupub/go-pdu
go-sundheit|github.com/AppsFlyer/go-sundheit
go-zero|github.com/zeromicro/go-zero
health|github.com/schigh/health/v2
jsonrpc|github.com/osamingo/jsonrpc/v2
k8gb|github.com/k8gb-io/k8gb
kitex|github.com/cloudwego/kitex
kratos|github.com/go-kratos/kratos/v3
liftbridge|github.com/liftbridge-io/liftbridge
lock|github.com/ubgo/lock
lura|github.com/luraproject/lura/v3
mqtt|github.com/mochi-mqtt/server/v2
nats-server|github.com/nats-io/nats-server/v2
opentelemetry-go-auto-instrumentation|github.com/alibaba/loongsuite-go
oras|oras.land/oras
outbox|github.com/oagudo/outbox
outboxer|github.com/italolelis/outboxer
raft|github.com/hashicorp/raft
rain|github.com/cenkalti/rain/v2
redislock|github.com/bsm/redislock
rpcplatform|github.com/nexcode/rpcplatform
rpcx|github.com/smallnest/rpcx
semaphore|github.com/jexia/semaphore/v2
servicepack|github.com/psyb0t/servicepack
sponge|github.com/go-dev-frame/sponge
tarmac|github.com/tarmac-project/tarmac
sdk-go|go.temporal.io/sdk
torrent|github.com/anacrolix/torrent
trpc-go|trpc.group/trpc-go/trpc-go
ddns|github.com/skibish/ddns
godns|github.com/TimothyYe/godns
email-verifier|github.com/AfterShip/email-verifier
go-email-normalizer|github.com/dimuska139/go-email-normalizer/v5
go-imap|github.com/BrianLeishman/go-imap
go-mail|github.com/wneessen/go-mail
go-message|github.com/emersion/go-message
go-premailer|github.com/vanng822/go-premailer
go-simple-mail|github.com/xhit/go-simple-mail/v2
go-spamcheck|github.com/psyb0t/go-spamcheck
hermes|github.com/matcornic/hermes
maddy|github.com/foxcpp/maddy
mailgun-go|github.com/mailgun/mailgun-go/v5
mailpit|github.com/axllent/mailpit
mailx|github.com/valord577/mailx
mox|github.com/mjl-/mox
go-smtp-mock|github.com/mocktools/go-smtp-mock/v2
verify|github.com/tickstem/verify
truemail-go|github.com/truemail-rb/truemail-go
anko|github.com/mattn/anko
cel-go|github.com/google/cel-go
ecal|github.com/krotik/ecal
expr|github.com/expr-lang/expr
frankenphp|github.com/dunglas/frankenphp
gentee|github.com/gentee/gentee
go-lua|github.com/Shopify/go-lua
goja|github.com/dop251/goja
golua|github.com/aarzilli/golua
gopher-lua|github.com/yuin/gopher-lua
gval|github.com/PaesslerAG/gval
prolog|github.com/ichiban/prolog
starlark-go|go.starlark.net
starlet|github.com/1set/starlet
tengo|github.com/d5/tengo/v2
wa|wa-lang.org/wa
ctxerrors|github.com/psyb0t/ctxerrors
emperror|emperror.dev/emperror
eris|github.com/rotisserie/eris
errors|emperror.dev/errors
errorx|github.com/joomcode/errorx
exception|github.com/rbrahul/exception
fault|github.com/Southclaws/fault
go-bruh|github.com/aisbergg/go-bruh
go|github.com/go-errr/go
go-multierror|github.com/hashicorp/go-multierror
metaerr|github.com/quantumcycle/metaerr
multierr|go.uber.org/multierr
oops|github.com/samber/oops
tracerr|github.com/ztrue/tracerr
afero|github.com/spf13/afero
afs|github.com/viant/afs
baraka|github.com/xis/baraka/v2
checksum|github.com/codingsince1985/checksum
copy|github.com/otiai10/copy
fastwalk|github.com/charlievieth/fastwalk
flop|github.com/homedepot/flop
gdu|github.com/dundee/gdu/v5
go-csv-tag|github.com/artonge/go-csv-tag/v2
go-exiftool|github.com/barasher/go-exiftool
go-gtfs|github.com/artonge/go-gtfs
go-wkhtmltopdf|github.com/SebastiaanKlippert/go-wkhtmltopdf
goflat|github.com/lzambarda/goflat
gofs|github.com/no-src/gofs
gopdfrab|github.com/voidrab/gopdfrab
gulter|github.com/adelowo/gulter
gut|github.com/1set/gut
gxpdf|github.com/coregx/gxpdf
higgs|github.com/dastoori/higgs
iso9660|github.com/kdomanski/iso9660
notify|github.com/rjeczalik/notify
opc|github.com/qmuntal/opc
parquet|github.com/parsyl/parquet
pathtype|github.com/jonchun/pathtype
pdfcpu|github.com/pdfcpu/pdfcpu
todotxt|github.com/1set/todotxt
vfs|github.com/c2fo/vfs/v7
accounting|github.com/leekchan/accounting
ach|github.com/moov-io/ach
bbgo|github.com/c9s/bbgo
bingx-go|github.com/tigusigalpa/bingx-go/v2
bitget-go|github.com/tigusigalpa/bitget-go
bybit-go|github.com/tigusigalpa/bybit-go
cnn-fear-and-greed-parse|github.com/wildsurfer/cnn-fear-and-greed-parse/v2
currency|github.com/bojanz/currency
dec128|github.com/jokruger/dec128
decimal|github.com/shopspring/decimal
eu-vat-rates-data-go|github.com/vatnode/eu-vat-rates-data-go
fpdecimal|github.com/nikolaydubina/fpdecimal
fpmoney|github.com/nikolaydubina/fpmoney
glassnode-go|github.com/tigusigalpa/glassnode-go
go-finance|github.com/alpeb/go-finance
go-money|github.com/Rhymond/go-money
go-nowpayments|github.com/matm/go-nowpayments
gobl|github.com/invopop/gobl
indicator|github.com/cinar/indicator/v2
kucoin-go|github.com/tigusigalpa/kucoin-go
ledger|github.com/formancehq/ledger
money|github.com/govalues/money
ofxgo|github.com/aclindsa/ofxgo
okx-go|github.com/tigusigalpa/okx-go
payme|github.com/jovandeginste/payme
paystack-sdk-go|github.com/samaasi/paystack-sdk-go/v2
techan|github.com/sdcoffey/techan
telegram-wallet-go|github.com/tigusigalpa/telegram-wallet-go
ticker|github.com/achannarasappa/ticker/v5
udecimal|github.com/quagmt/udecimal
vat|github.com/dannyvankooten/vat
conform|github.com/leebenson/conform
form|github.com/go-playground/form/v4
formam|github.com/monoculum/formam/v3
gbind|github.com/bdjimmy/gbind
csrf|github.com/gorilla/csrf
httpin|github.com/ggicci/httpin
nosurf|github.com/justinas/nosurf
qs|github.com/sonh/qs
queryparam|github.com/tomwright/queryparam/v4
roamer|github.com/slipros/roamer
fp-go|github.com/repeale/fp-go
fpGo|github.com/TeaEntityLab/fpGo/v2
fuego|github.com/seborama/fuego/v12
FuncFrog|github.com/koss-null/funcfrog
g|github.com/enetx/g
go-functional|github.com/BooleanCat/go-functional/v2
gofp|github.com/rbrahul/gofp
mo|github.com/samber/mo
underscore|github.com/rjNemo/underscore
valor|github.com/phelmkamp/valor
ark|github.com/mlange-42/ark
due|github.com/dobyte/due/v2
ebiten|github.com/hajimehoshi/ebiten/v2
ecs|github.com/andygeiss/ecs
engo|github.com/EngoEngine/engo
fantasyname|github.com/s0rg/fantasyname
engine|github.com/g3n/engine
go-sdl2|github.com/veandco/go-sdl2
go3d|github.com/ungerik/go3d
gogpu|github.com/gogpu/gogpu
wgpu|github.com/gogpu/wgpu
goke|github.com/kjkrol/goke/v3
goworld|github.com/xiaonanln/goworld
grid|github.com/s0rg/grid
nano|github.com/lonng/nano
oak|github.com/oakmound/oak/v4
pi|github.com/elgopher/pi
pitaya|github.com/topfreegames/pitaya/v3
pixel|github.com/gopxl/pixel/v2
prototype|github.com/gonutz/prototype
sceneCamera|github.com/donomii/sceneCamera
tile|github.com/kelindar/tile
apispec|github.com/ehabterra/apispec
convergen|github.com/reedom/convergen/v8
copygen|github.com/switchupcb/copygen
go-apispec|github.com/antst/go-apispec
go-enum|github.com/abice/go-enum
go-enum-encoding|github.com/nikolaydubina/go-enum-encoding
go-linq|github.com/ahmetb/go-linq/v5
goderive|awalterschulze.org/go/goderive
goverter|github.com/jmattheis/goverter
gowrap|github.com/hexdigest/gowrap
interfaces|github.com/rjeczalik/interfaces
jennifer|github.com/dave/jennifer
oapi-codegen|github.com/oapi-codegen/oapi-codegen/v2
protoc-gen-httpgo|github.com/MUlt1mate/protoc-gen-httpgo
protoc-gen-mcp|github.com/easyp-tech/protoc-gen-mcp
typeregistry|github.com/xiaoxin01/typeregistry
borders|github.com/kpfaulkner/borders
geoos|github.com/spatial-go/geoos
geoserver|github.com/hishamkaram/geoserver/v2
gismanager|github.com/hishamkaram/gismanager/v2
godal|github.com/airbusgeo/godal
h3-go|github.com/uber/h3-go/v4
go-geojson2h3|github.com/mmadfox/go-geojson2h3
go-h3geo-dist|github.com/mmadfox/go-h3geo-dist
mbtileserver|github.com/consbio/mbtileserver
osm|github.com/paulmach/osm
pbf|m4o.io/pbf/v2
s2-geojson|github.com/pantrif/s2-geojson
geo|github.com/golang/geo
simplefeatures|github.com/peterstace/simplefeatures
tile38|github.com/tidwall/tile38
web-mercator-projection|github.com/jorelosorio/web-mercator-projection
wgs84|github.com/wroge/wgs84
bunster|github.com/yassinebenaid/bunster
c4go|github.com/Konstantin8105/c4go
cxgo|github.com/gotranspile/cxgo
esp32-transpiler|github.com/andygeiss/esp32-transpiler
f4go|github.com/Konstantin8105/f4go
go2hx|github.com/go2hx/go4hx
gopherjs|github.com/gopherjs/gopherjs
anchor|github.com/kyuff/anchor
ants|github.com/panjf2000/ants/v2
artifex|github.com/mborders/artifex
async|github.com/yaitoo/async
async-job|github.com/lab210-dev/async-job
autopool|github.com/AshvinBambhaniya/autopool/v2
breaker|github.com/kamilsk/breaker
channelify|github.com/ddelizia/channelify
conc|github.com/sourcegraph/conc
concurrency-limiter|github.com/vivek-ng/concurrency-limiter
conexec|github.com/ITcathyh/conexec
cyclicbarrier|github.com/marusama/cyclicbarrier
execpool|github.com/hexdigest/execpool
flowmatic|github.com/carlmjohnson/flowmatic
go-accumulator|github.com/nar10z/go-accumulator/v2
go-actor|github.com/vladopajic/go-actor
go-floc|github.com/workanator/go-floc/v3
go-future|github.com/jizhuozhi/go-future
go-trylock|github.com/subchen/go-trylock/v2
go-waitgroup|github.com/pieterclaerhout/go-waitgroup
go-workerpool|github.com/zenthangplus/go-workerpool
goccm|github.com/zenthangplus/goccm
gohive|github.com/loveleshsharma/gohive
gollback|github.com/vardius/gollback
goscade|github.com/ognick/goscade/v2
gowl|github.com/hamed-yousefi/gowl
goworker|github.com/benmanns/goworker
gowp|github.com/xxjwxc/gowp
gpool|github.com/sherifabdlnaby/gpool
hands|github.com/duanckham/hands
Hunch|github.com/aaronjan/hunch
kyoo|github.com/dirkaholic/kyoo
errgroup|github.com/neilotoole/errgroup
nursery|github.com/arunsworld/nursery
pond|github.com/alitto/pond/v2
powerlock|github.com/donomii/powerlock
rill|github.com/destel/rill
routine|github.com/timandy/routine
threadpool|github.com/shettyh/threadpool
tunny|github.com/Jeffail/tunny
worker-pool|github.com/vardius/worker-pool/v2
workerpool|github.com/gammazero/workerpool
app|github.com/maxence-charriere/go-app/v11
cimgui-go|github.com/AllenDang/cimgui-go
core|cogentcore.org/core
darwinkit|github.com/progrium/darwinkit
energy|github.com/energye/energy/v3
fyne|fyne.io/fyne/v2
ui|github.com/gogpu/ui
html5tag|github.com/goradd/html5tag
gotk3|github.com/gotk3/gotk3
gowd|github.com/dtylman/gowd
proton|github.com/CzaxStudio/proton
qt|github.com/therecipe/qt
spot|github.com/roblillack/spot
unison|github.com/richardwilkes/unison
appindicator|github.com/gopherlibs/appindicator
systray|github.com/gogpu/systray
activity-tracker|github.com/prashantgupta24/activity-tracker
mac-sleep-notifier|github.com/prashantgupta24/mac-sleep-notifier
robotgo|github.com/go-vgo/robotgo
trayhost|github.com/shurcooL/trayhost
zenity|github.com/ncruces/zenity
arduino-cli|github.com/arduino/arduino-cli
emgo|github.com/ziutek/emgo
ghw|github.com/jaypipes/ghw
go-osc|github.com/hypebeast/go-osc
go-rpio|github.com/stianeikeland/go-rpio/v4
goroslib|github.com/bluenviron/goroslib/v2
joystick|github.com/0xcafed00d/joystick
moody|github.com/dinakars777/moody
sysinfo|github.com/zcalusic/sysinfo
bild|github.com/anthonynsimon/bild
cameron|github.com/aofei/cameron
canvas|github.com/tdewolff/canvas
color-extractor|github.com/marekm4/color-extractor
darkroom|github.com/gojek/darkroom
eagle-image-api|github.com/nicobistolfi/eagle-image-api
gift|github.com/disintegration/gift
gltf|github.com/qmuntal/gltf
go-cairo|github.com/ungerik/go-cairo
go-gd|github.com/bolknote/go-gd/v2
go-qrcode|github.com/yeqown/go-qrcode/v2
go-webp|github.com/kolesa-team/go-webp
gocv|gocv.io/x/gocv
gg|github.com/gogpu/gg
goimagehash|github.com/corona10/goimagehash
govatar|github.com/o1egl/govatar
govips|github.com/davidbyttow/govips/v2
gowitness|github.com/sensepost/gowitness
gridder|github.com/shomali11/gridder
imagick|gopkg.in/gographics/imagick.v2
imaginary|github.com/h2non/imaginary
imaging|github.com/disintegration/imaging
imagor|github.com/cshum/imagor
mort|github.com/aldor007/mort
mpo|github.com/donatj/mpo
nativewebp|github.com/HugoSmits86/nativewebp
picfit|github.com/thoas/picfit
scout|github.com/jonoton/scout
smartcrop|github.com/muesli/smartcrop
steganography|github.com/auyer/steganography
svgo|github.com/ajstarks/svgo
transformimgs|github.com/Pixboost/transformimgs/v8
webp-server|github.com/mehdipourfar/webp-server
connectordb|github.com/heedy/heedy
ekuiper|github.com/lf-edge/ekuiper/v2
gobot|gobot.io/x/gobot
huego|github.com/amimof/huego
rulego|github.com/rulego/rulego
shifu|github.com/edgenesis/shifu
smart-home|github.com/e154/smart-home
cdule|github.com/deepaksinghvi/cdule
cheek|github.com/bart6114/cheek
clockwerk|github.com/onatm/clockwerk
cronticker|github.com/krayzpipes/cronticker
go-cron|github.com/netresearch/go-cron
go-job|github.com/cybergarage/go-job
go-quartz|github.com/reugn/go-quartz
go-scheduler|github.com/pardnchiu/go-scheduler
`
