package registry

// DefaultPackages is deliberately data-driven so expanding the catalog does
// not require changing resolver logic. These are high-confidence ecosystem
// entries; unknown names still use the discovery fallback.
func DefaultPackages() []Package {
	packages := []Package{
		{Name: "gin", Aliases: []string{"gin-gonic"}, Module: "github.com/gin-gonic/gin", Type: Library, Verified: true, Description: "HTTP web framework", Categories: []string{"web", "http", "framework"}, Latest: "v1.10.0", License: "MIT", Stars: 80000},
		{Name: "fiber", Aliases: []string{"fiber-go"}, Module: "github.com/gofiber/fiber/v2", Type: Library, Verified: true, Description: "Express-inspired web framework", Categories: []string{"web", "http", "framework"}, License: "MIT", Stars: 35000},
		{Name: "echo", Module: "github.com/labstack/echo/v4", Type: Library, Verified: true, Description: "High performance, extensible web framework", Categories: []string{"web", "http", "framework"}, License: "MIT", Stars: 30000},
		{Name: "chi", Aliases: []string{"go-chi"}, Module: "github.com/go-chi/chi/v5", Type: Library, Verified: true, Description: "Lightweight HTTP router", Categories: []string{"web", "http", "router"}, License: "MIT", Stars: 19000},
		{Name: "gorilla-mux", Aliases: []string{"mux"}, Module: "github.com/gorilla/mux", Type: Library, Verified: true, Description: "HTTP request router and dispatcher", Categories: []string{"web", "http", "router"}, License: "BSD-3-Clause", Stars: 21000},
		{Name: "httprouter", Module: "github.com/julienschmidt/httprouter", Type: Library, Verified: true, Description: "High performance HTTP request router", Categories: []string{"web", "http", "router"}, License: "MIT", Stars: 18000},
		{Name: "cobra", Module: "github.com/spf13/cobra", Type: Library, Verified: true, Description: "Modern CLI framework", Categories: []string{"cli", "framework"}, License: "Apache-2.0", Stars: 39000},
		{Name: "urfave-cli", Aliases: []string{"cli"}, Module: "github.com/urfave/cli/v2", Type: Library, Verified: true, Description: "Simple and fast command line interface package", Categories: []string{"cli", "framework"}, License: "MIT", Stars: 22000},
		{Name: "kong", Module: "github.com/alecthomas/kong", Type: Library, Verified: true, Description: "Command line parser for Go", Categories: []string{"cli", "framework"}, License: "MIT", Stars: 5000},
		{Name: "bubbletea", Aliases: []string{"tui"}, Module: "github.com/charmbracelet/bubbletea", Type: Library, Verified: true, Description: "Powerful little TUI framework", Categories: []string{"cli", "tui"}, License: "MIT", Stars: 28000},
		{Name: "gorm", Module: "gorm.io/gorm", Type: Library, Verified: true, Description: "The fantastic ORM library for Go", Categories: []string{"database", "orm"}, License: "MIT", Stars: 38000},
		{Name: "sqlx", Module: "github.com/jmoiron/sqlx", Type: Library, Verified: true, Description: "Extensions to database/sql", Categories: []string{"database", "sql"}, License: "MIT", Stars: 17000},
		{Name: "ent", Module: "entgo.io/ent", Type: Library, Verified: true, Description: "Entity framework for Go", Categories: []string{"database", "orm"}, License: "Apache-2.0", Stars: 16000},
		{Name: "bun", Module: "github.com/uptrace/bun", Type: Library, Verified: true, Description: "SQL-first Go ORM", Categories: []string{"database", "orm"}, License: "BSD-2-Clause", Stars: 5000},
		{Name: "pgx", Module: "github.com/jackc/pgx/v5", Type: Library, Verified: true, Description: "PostgreSQL driver and toolkit", Categories: []string{"database", "postgresql", "sql"}, License: "MIT", Stars: 12000},
		{Name: "mysql-driver", Aliases: []string{"mysql"}, Module: "github.com/go-sql-driver/mysql", Type: Library, Verified: true, Description: "Go MySQL driver", Categories: []string{"database", "mysql", "sql"}, License: "MPL-2.0", Stars: 15000},
		{Name: "libpq", Module: "github.com/lib/pq", Type: Library, Verified: true, Description: "Pure Go Postgres driver", Categories: []string{"database", "postgresql", "sql"}, License: "MIT", Stars: 10000},
		{Name: "bcrypt", Aliases: []string{"password-hashing", "crypto-bcrypt"}, Module: "golang.org/x/crypto", Package: "golang.org/x/crypto/bcrypt", Type: Library, Verified: true, Description: "Password hashing with bcrypt", Categories: []string{"security", "authentication", "crypto"}, License: "BSD-3-Clause", Stars: 18000},
		{Name: "jwt", Aliases: []string{"json-web-token"}, Module: "github.com/golang-jwt/jwt/v5", Type: Library, Verified: true, Description: "JSON Web Token implementation", Categories: []string{"security", "authentication"}, License: "MIT", Stars: 7000},
		{Name: "oauth2", Aliases: []string{"oauth"}, Module: "golang.org/x/oauth2", Type: Library, Verified: true, Description: "Go OAuth2 client library", Categories: []string{"security", "authentication"}, License: "BSD-3-Clause", Stars: 9000},
		{Name: "casbin", Module: "github.com/casbin/casbin/v2", Type: Library, Verified: true, Description: "Authorization library for Go", Categories: []string{"security", "authorization"}, License: "Apache-2.0", Stars: 18000},
		{Name: "grpc", Module: "google.golang.org/grpc", Type: Library, Verified: true, Description: "HTTP/2 based RPC framework", Categories: []string{"networking", "rpc"}, License: "Apache-2.0", Stars: 21000},
		{Name: "websocket", Aliases: []string{"gorilla-websocket"}, Module: "github.com/gorilla/websocket", Type: Library, Verified: true, Description: "WebSocket implementation for Go", Categories: []string{"networking", "websocket"}, License: "BSD-2-Clause", Stars: 22000},
		{Name: "nats", Module: "github.com/nats-io/nats.go", Type: Library, Verified: true, Description: "Cloud native messaging system client", Categories: []string{"networking", "messaging"}, License: "Apache-2.0", Stars: 5000},
		{Name: "redis", Aliases: []string{"go-redis"}, Module: "github.com/redis/go-redis/v9", Type: Library, Verified: true, Description: "Redis client for Go", Categories: []string{"database", "cache", "networking"}, License: "BSD-2-Clause", Stars: 20000},
		{Name: "kafka-go", Aliases: []string{"kafka"}, Module: "github.com/segmentio/kafka-go", Type: Library, Verified: true, Description: "Kafka client library", Categories: []string{"networking", "messaging"}, License: "MIT", Stars: 8000},
		{Name: "zerolog", Aliases: []string{"logging"}, Module: "github.com/rs/zerolog", Type: Library, Verified: true, Description: "Zero-allocation JSON logger", Categories: []string{"logging", "observability"}, License: "MIT", Stars: 10000},
		{Name: "zap", Module: "go.uber.org/zap", Type: Library, Verified: true, Description: "Blazing fast structured logging", Categories: []string{"logging", "observability"}, License: "MIT", Stars: 20000},
		{Name: "viper", Module: "github.com/spf13/viper", Type: Library, Verified: true, Description: "Configuration solution for Go applications", Categories: []string{"configuration"}, License: "MIT", Stars: 28000},
		{Name: "validator", Aliases: []string{"go-playground-validator"}, Module: "github.com/go-playground/validator/v10", Type: Library, Verified: true, Description: "Struct and field validation", Categories: []string{"validation"}, License: "MIT", Stars: 18000},
		{Name: "testify", Module: "github.com/stretchr/testify", Type: Library, Verified: true, Description: "Toolkit for Go testing", Categories: []string{"testing"}, License: "MIT", Stars: 23000},
		{Name: "wire", Module: "github.com/google/wire", Type: Library, Verified: true, Description: "Compile-time dependency injection", Categories: []string{"development", "dependency-injection"}, License: "Apache-2.0", Stars: 18000},
		{Name: "air", Aliases: []string{"live-reload"}, Module: "github.com/air-verse/air", Type: Command, Verified: true, Description: "Live reload for Go applications", Categories: []string{"developer-tools", "live-reload"}, License: "GPL-3.0", Stars: 16000},
		{Name: "golangci-lint", Aliases: []string{"go-lint"}, Module: "github.com/golangci/golangci-lint/cmd/golangci-lint", Type: Command, Verified: true, Description: "Fast Go linters runner", Categories: []string{"developer-tools", "linting"}, License: "GPL-3.0", Stars: 17000},
		{Name: "mockgen", Module: "go.uber.org/mock/mockgen", Type: Command, Verified: true, Description: "Go mock generator", Categories: []string{"developer-tools", "testing"}, License: "Apache-2.0", Stars: 3000},
		{Name: "swag", Module: "github.com/swaggo/swag/cmd/swag", Type: Command, Verified: true, Description: "Swagger documentation generator", Categories: []string{"developer-tools", "documentation"}, License: "MIT", Stars: 12000},
		{Name: "sqlc", Module: "github.com/sqlc-dev/sqlc/cmd/sqlc", Type: Command, Verified: true, Description: "Generate type-safe Go from SQL", Categories: []string{"developer-tools", "database"}, License: "MIT", Stars: 13000},
		{Name: "migrate", Aliases: []string{"golang-migrate"}, Module: "github.com/golang-migrate/migrate/v4/cmd/migrate", Type: Command, Verified: true, Description: "Database migration CLI", Categories: []string{"developer-tools", "database"}, License: "MIT", Stars: 15000},
		{Name: "buf", Module: "github.com/bufbuild/buf/cmd/buf", Type: Command, Verified: true, Description: "Protobuf management tool", Categories: []string{"developer-tools", "protobuf"}, License: "Apache-2.0", Stars: 9000},
		{Name: "protoc-gen-go", Module: "google.golang.org/protobuf/cmd/protoc-gen-go", Type: Command, Verified: true, Description: "Protocol Buffers Go code generator", Categories: []string{"developer-tools", "protobuf"}, License: "BSD-3-Clause", Stars: 10000},
		{Name: "goimports", Module: "golang.org/x/tools/cmd/goimports", Type: Command, Verified: true, Description: "Formats Go code and updates imports", Categories: []string{"developer-tools", "formatting"}, License: "BSD-3-Clause", Stars: 8000},
		{Name: "staticcheck", Module: "honnef.co/go/tools/cmd/staticcheck", Type: Command, Verified: true, Description: "Advanced Go static analysis", Categories: []string{"developer-tools", "linting"}, License: "MIT", Stars: 10000},
		{Name: "govulncheck", Module: "golang.org/x/vuln/cmd/govulncheck", Type: Command, Verified: true, Description: "Find known vulnerabilities in Go code", Categories: []string{"developer-tools", "security"}, License: "BSD-3-Clause", Stars: 4000},
		{Name: "delve", Aliases: []string{"dlv"}, Module: "github.com/go-delve/delve/cmd/dlv", Type: Command, Verified: true, Description: "Debugger for the Go programming language", Categories: []string{"developer-tools", "debugging"}, License: "MIT", Stars: 19000},
		{Name: "templ", Module: "github.com/a-h/templ/cmd/templ", Type: Command, Verified: true, Description: "Type-safe HTML templating language", Categories: []string{"web", "developer-tools"}, License: "MIT", Stars: 7000},
		{Name: "go-releaser", Aliases: []string{"goreleaser"}, Module: "github.com/goreleaser/goreleaser", Type: Command, Verified: true, Description: "Release automation for Go projects", Categories: []string{"developer-tools", "release"}, License: "MIT", Stars: 15000},
		{Name: "x-crypto", Module: "golang.org/x/crypto", Type: Library, Verified: true, Description: "Supplementary cryptography packages", Categories: []string{"security", "crypto"}, License: "BSD-3-Clause", Stars: 18000},
		{Name: "x-net", Module: "golang.org/x/net", Type: Library, Verified: true, Description: "Supplementary networking packages", Categories: []string{"networking", "http"}, License: "BSD-3-Clause", Stars: 12000},
		{Name: "x-sync", Module: "golang.org/x/sync", Type: Library, Verified: true, Description: "Supplementary concurrency primitives", Categories: []string{"concurrency"}, License: "BSD-3-Clause", Stars: 7000},
		{Name: "x-text", Module: "golang.org/x/text", Type: Library, Verified: true, Description: "Internationalization and text packages", Categories: []string{"text", "i18n"}, License: "BSD-3-Clause", Stars: 5000},
	}
	return append(packages, supplementalPackages(packages)...)
}
