package registry

import (
	"path"
	"strings"
)

// supplementalModuleCatalog is sourced from a curated Go ecosystem index.
// The hand-curated entries in default.go override these entries when names
// overlap and carry richer metadata such as license and health scores.
var supplementalModuleCatalog = `
+avelino/awesome-go
pancsta/asyncmachine-go
ergo-services/ergo
tochemey/goakt
anthdm/hollywood
asynkron/protoactor-go
saivedant169/aegisflow
colin4k1024/aetheris
agenticenv/agent-sdk-go
tphakala/agy-mcp
joakimcarlsson/ai
ferro-labs/ai-gateway
philippgille/chromem-go
rhgs/crewai-go
dakera-ai/dakera-go
zendev-sh/goai
enterpilot/gomodel
hrygo/hotplex
gojargo/jargo
mochow13/keen-code
tmc/langchaingo
smallnest/langgraphgo
alib8b8/llm-box
mudler/localai
harshaneel/localaik
mark3labs/mcp-go
jmorganca/ollama
presbrey/ollamafarm
oluwajubelo1/otellix
ad3bay0c/routex
davidbelicza/semantic-search
thousandflowers/skillreaper
smeldr/core
edouard-claude/snip
trpc-group/trpc-agent-go
zoharbabin/web-researcher-mcp
zendev-sh/zenflow
gopxl/beep
mewkiz/flac
comcast/gaad
tphakala/go-aac
tphakala/go-audio-resampler
tphakala/go-flac
leberkleber/go-mpris
tphakala/go-opus
gojargo/go-resample
tphakala/go-wav
dylanmeeus/goaudio
dh1tw/gosamplerate
bogem/id3v2
gen2brain/malgo
tosone/minimp3
go-music-theory/music-theory
hajimehoshi/oto
gordonklaus/portaudio
voxray-ai/voxray
volatiletech/authboss
go-authgate/authgate
essentialkaos/branca
tuupola/branca-spec
hsluoyz/casbin
mengzhuo/cookiestxt
jferrl/go-githubauth
shaj13/go-guardian
melvinodsa/go-iam
go-jose/go-jose
deatil/go-jwt
pardnchiu/go-jwt
leodip/goiabada
dghubble/gologin
mikespook/gorbac
kwynto/gosession
markbates/goth
abraithwaite/jeff
pascaldekloe/jwt
cristalhq/jwt
adam-hanna/jwt-auth
golang-jwt/jwt
lestrrat-go/jwx
ory/keto
tarent/loginsrv
pthm/melange
golang/oauth2
zitadel/oidc
openfga/openfga
openshift/osin
grijul/otpgen
jltorresm/otpgo
o1egl/paseto
xyproto/permissions
sonicroshan/scope
alexedwards/scs
chmike/securecookie
icza/session
adam-hanna/sessions
swithek/sessionup
brianvoe/sjwt
authzed/spicedb
vkuznet/x509proxy
cometbft/cometbft
cosmos/cosmos-sdk
gnolang/gno
ethereum/go-ethereum
limechain/gosemble
chainsafe/gossamer
ipfs/kubo
lightningnetwork/lnd
blinklabs-io/nview
pactus-project/pactus
gagliardetto/solana-go
tendermint/tendermint
kslamph/tronlib
diamondburned/arikawa
go-telegram/bot
niconex/echotron
oklahomer/go-sarah
mr-linch/go-tg
gempir/go-twitch-irc
onrik/micha
innogames/slack-bot
slack-io/slacker
tucnak/telebot
kslamph/teleflow
mymmrac/telego
go-telegram-bot-api/telegram-bot-api
enetx/tg
wabarc/wayback
rekurt/ymsdk
wisp-trading/wisp
gopinath-langote/1build
cosmtrek/air
guilhermecaruso/anko
maxclaus/gaper
kcmvp/gob
goyek/goyek
magefile/mage
tj/mmake
tockins/realize
rexrun-dev/rex
go-task/task
taskctl/taskctl
joerdav/xc
guptarohit/asciigraph
logrusorgru/aurora
box-cli-maker/box-cli-maker
evertras/bubble-table
charmbracelet/bubbles
charmbracelet/bubbletea
arceus-7/chroma16
alfiankan/crab-config-files-templating
wzshiming/ctc
antonmedv/fx
workanator/go-ataman
mattn/go-colorable
daviddengcn/go-colortext
mattn/go-isatty
abusomani/go-palette
c-bata/go-prompt
jonathanslenders/python-prompt-toolkit
grindlemire/go-tui
jroimartin/gocui
labstack/gommon
gookit/color
iyashjayesh/goscaf
lazynop/lazyenv
agmonetti/lazyteams
charmbracelet/lipgloss
loom-go/loom
cyucelen/marker
vbauerster/mpb
phoenix-tui/phoenix
schollz/progressbar
pterm/pterm
alexeyco/simpletable
briandowns/spinner
cheynewallace/tabby
tomlazar/table
nsf/termbox-go
mum4k/termdash
gizak/termui
muesli/termenv
yaronn/blessed-contrib
gosuri/uilive
gosuri/uiprogress
gosuri/uitable
charmbracelet/vhs
theckman/yacspin
cristalhq/acmd
akamensky/argparse
cosiner/argv
gigurra/boa
rsteube/carapace
rsteube/carapace-bin
rsteube/carapace-spec
tucnak/climax
leaanthony/clir
posener/cmd
hedzr/cmdr
spf13/cobra
rainu/go-command-chain
jaffee/commandeer
posener/complete
reeflective/console
dnote/dnote
elves/elvish
codingconcepts/env
integrii/flaggy
sgreben/flagvar
agilira/flash-flags
jon-codes/getopt
salvuccifacundo/go-arch
alexflint/go-arg
jessevdk/go-flags
davidgamba/go-getoptions
nyaosorg/go-readline-ny
devfacet/gocmd
napalu/goopt
hashicorp/cli
hidevopsio/hiboot
liujianping/job
alecthomas/kingpin
peterh/liner
jxskiss/mcli
amjadjibon/memsh
mkideal/cli
jawher/mow.cli
steevin/neuron-cli
bcdxn/opencli
nanovms/ops
agilira/orpheus
spf13/pflag
reeflective/readline
octago/sflags
leodido/structcli
antham/strumt
bobg/subcmd
teris-io/cli
urfave/cli
mszostok/version
dixonwille/wlog
dixonwille/wmenu
cristalhq/aconfig
agilira/argus
azure/appconfiguration-goprovider
wkhere/bcl
ilyakaznacheev/cleanenv
jeremyloy/config
num30/config
andreiavrammsd/config
borudar/configuration
sherifabdlnaby/configuro
greencoda/confiq
heetch/confita
the4thamigo-uk/conflate
atelpis/enflag
caarlos0/env
junk1tm/env
syntaqx/env
vrischmann/envconfig
antham/envh
yuseferi/envyaml
kkyr/fig
sakirsensoy/genv
deatil/go-array
paddlehq/go-aws-ssm
dsbasko/go-cfg
thomasobenaus/go-conf
mordateam/go-config
go-external-config/go
go-external-config/aws
go-external-config/consul
go-external-config/vault
subpop/go-ini
ianlopshire/go-ssm-config
ufoscout/go-up
jagerente/gocfg
fulldump/goconfig
joho/godotenv
psyb0t/goenv
golobby/config
one-com/gone
milad-abbasi/gonfig
psyb0t/gonfiguration
gookit/config
beatlabs/harvester
hedzr/store
hjson/hjson-go
gurkankaymak/hocon
go-ini/ini
wlevene/ini
kelseyhightower/envconfig
knadh/koanf
nil-go/konf
lalamove/konfig
alecthomas/kong
nasermirzaei89/env
muir/nfigure
goraz/onion
yiling-j/piper
bytedance/sonic
oblq/swap
diegomarangoni/typenv
omeid/uconfig
spf13/viper
adrg/xdg
romshark/yamagiconf
chaindead/zerocfg
bleenco/abstruse
ovh/cds
opnlabs/dot
drone/drone
gha-common/go-beautiful-html-coverage
jidicula/go-fuzz-action
s0ders/go-semver-release
nikogura/gomason
gotesttools/gotestfmt
mattn/goveralls
raviqqe/muffet
lycheeverse/lychee
go-playground/overalls
pikoci/pikoci
lawrencewoodman/roveralls
woodpecker-ci/woodpecker
napsy/go-css
wellington/go-libsass
benthosdev/benthos
cloudquery/cloudquery
gkoos/confluence2md
jf-tech/omniparser
iancmcc/bingo
zhuangsirui/binpacker
yourbasic/bit
superwhiskers/crunch
amallia/go-ef
roaringbitmap/roaring
kelindar/bitmap
bits-and-blooms/bitset
bits-and-blooms/bloom
zhenjl/bloom
yourbasic/bloom
oldpanda/bloomfilter
tylertreat/boomfilters
linvon/cuckoo-filter
seiflotfy/cuckoofilter
ribbonfilter/ribbongo
thetannerryan/ring
shady831213/algorithms
workiva/go-datastructures
emirpasic/gods
liyue201/gostl
alvii147/gloop
yaa110/goterator
disksing/iter
lrita/cmap
mhmtszr/concurrent-swiss-map
srfrog/dict
donomii/genericsyncmap
lucmq/go-shelve
goradd/maps
lyonnee/hmap
bobg/combo
free/concurrent-writer
seiflotfy/count-min-log
enetx/fsm
cocoonspace/fsm
nwillc/genfuncs
bobg/go-generics
hailocab/go-geoindex
francesconi/go-rampart
aurelien-rainone/go-rquad
barweiss/go-tuple
daichi-m/go18ds
xxjwxc/gofal
esimov/gogu
kniren/gota
emvi/hide
axiomhq/hyperloglog
s0rg/quadtree
twharmon/slices
kak-tus/nan
emvi/null
gurukami/typ
aalpar/deheap
edwingeng/deque
gammazero/deque
vodolaz095/dqueue
enriquebris/goconcurrentqueue
hatchet-dev/hatchet
koss-null/list
embano1/memlog
adrianbrad/queue
ihebu/dsu
deckarep/golang-set
zoumo/goset
studiosol/set
blevesearch/bleve
plar/go-adaptive-radix-tree
hbollon/go-edlib
agext/levenshtein
agnivade/levenshtein
blackrabbitt/mspm
monaxgt/parsefields
viant/ptrie
gammazero/radixtree
derekparker/trie
aio-arch/graphlib
bobg/hashsplit
bobg/merkle
mauricegit/skiplist
gansidui/skiplist
huandu/skiplist
igrmk/treemap
tejzpr/ordered-concurrently
nazar256/parapipe
hyfather/pipeline
nxdir-s/pipelines
iwanbk/bcache
allegro/bigcache
muesli/cache2go
faabiosr/cachego
oastuff/clusteredbigcache
oracle/coherence-go-client
codingsince1985/couchcache
echovault/echovault
hugocarreira/easycache
victoriametrics/fastcache
bluele/gcache
ulovecode/gdcache
viney-shih/go-cache
elastic/go-freelru
szyhf/go-gcache
orlovevgeny/go-mcache
eko/gocache
yuseferi/gocache
golang/groupcache
mdaliyan/icache
erni27/imcache
mgtv-tech/jetcache-go
no-src/nscache
maypok86/otter
naughtygopher/pocache
dgraph-io/ristretto
viccon/sturdyc
yiling-j/theine-go
zekrotja/timedmap
jellydator/ttlcache
cheshir/ttlcache
dgraph-io/badger
etcd-io/bbolt
tidwall/buntdb
ostafen/clover
cockroachdb/cockroach
claygod/coffer
kelindar/column
covenantsql/covenantsql
paranoidguy/databunker
dgraph-io/dgraph
dicedb/dice
peterbourgon/diskv
dolthub/dolt
krotik/eliasdb
vinicius-lino-figueiredo/gedb
glebarez/go-sqlite
hdt3213/godis
syndtr/goleveldb
google/leveldb
jameycribbs/hare
codenotary/immudb
influxdb/influxdb
siddontang/ledisdb
jmhodges/levigo
amit-davidson/libradb
lindb/lindb
flower-corp/lotusdb
lynxbase/lynxdb
qyiun666/memhop
milvus-io/milvus
richardknop/minisql
couchbase/moss
aymanhs/nanotdb
feichai0017/nokv
orneryd/nornicdb
xujiajun/nutsdb
objectbox/objectbox-go
cockroachdb/pebble
fern4lvarez/piladb
akrylysov/pogreb
prometheus/prometheus
recoilme/pudge
nalgeon/redka
roseduan/rosedb
xgzlucario/rotom
rqlite/rqlite
rafaeljesus/tempdb
pingcap/tidb
houzuoguo/tiedot
unit-io/unitdb
chrislusf/vasto
victoriametrics/victoriametrics
ariga/atlas
`

func supplementalPackages(existing []Package) []Package {
	known := make(map[string]bool, len(existing))
	for _, pkg := range existing {
		known[strings.ToLower(pkg.Name)] = true
		known[strings.ToLower(pkg.Module)] = true
	}
	out := make([]Package, 0, len(supplementalModuleCatalog))
	for _, module := range strings.Fields(supplementalModuleCatalog) {
		name := path.Base(module)
		if name == "" || known[strings.ToLower(name)] || known[strings.ToLower(module)] {
			continue
		}
		known[strings.ToLower(name)] = true
		known[strings.ToLower(module)] = true
		out = append(out, Package{
			Name:          name,
			Module:        module,
			Type:          Library,
			InstallMethod: GoGet,
			Verified:      true,
			Description:   "Curated Go ecosystem package",
			Categories:    []string{"ecosystem"},
		})
	}
	return out
}
